packages:
  - 'main'
minimumReleaseAge: 0
allowBuilds:
  better-sqlite3: true
  cpu-features: true
  esbuild: true
  protobufjs: true
  sharp: true
  silk-sdk: true
  skia-canvas: true
  ssh2: true

overrides:
  'brace-expansion': '5.0.6'
  'esbuild': '0.28.0'
  'ws': '8.20.1'
