import { runtimeFileIO } from '../bun-file-io.js'
import { getLogger } from '../shared-runtime.js'
import { spawnFileWithBun } from './bun-spawn.js'

const bunRuntime = (globalThis as typeof globalThis & {
  Bun: {
    env: Record<string, string | undefined>
    gunzipSync(input: Uint8Array): Uint8Array
  }
}).Bun
const joinPath = (...parts: string[]) => parts.filter(Boolean).join('/').replaceAll(/\/+/g, '/')

const logger = getLogger('TGSConverter')

export default async function tgsToGif(tgsPath: string, outputPath?: string): Promise<string> {
  const outPath = outputPath || tgsPath.replace(/\.tgs$/i, '.gif')
  const tempDir = await runtimeFileIO.mkdtemp(joinPath(bunRuntime.env.TMPDIR || '/tmp', 'tgs-'))

  try {
    logger.debug(`[tgs2gif] Converting ${tgsPath} to ${outPath}`)

    // 1. 读取并解压TGS文件（TGS = gzipped Lottie JSON）
    const tgsBuffer = new Uint8Array(await runtimeFileIO.readBytes(tgsPath))
    const lottieJson = new TextDecoder().decode(bunRuntime.gunzipSync(tgsBuffer))
    const jsonPath = joinPath(tempDir, 'animation.json')
    await runtimeFileIO.write(jsonPath, lottieJson)
    logger.debug(`[tgs2gif] TGS decompressed to ${jsonPath}`)

    // 2. 使用lottie_to_png渲染每一帧为PNG
    logger.debug(`[tgs2gif] Rendering frames with lottie_to_png...`)

    await spawnFileWithBun('/usr/bin/lottie_to_png', [
      '--width',
      '512',
      '--height',
      '512',
      '--output',
      tempDir,
      jsonPath,
    ])

    // 3. 收集生成的PNG文件
    const allFiles = await runtimeFileIO.readdir(tempDir)
    const pngFiles = allFiles
      .filter(f => f.endsWith('.png'))
      .sort()
      .map(f => joinPath(tempDir, f))

    if (pngFiles.length === 0) {
      throw new Error('No PNG frames generated by lottie_to_png')
    }

    logger.debug(`[tgs2gif] Generated ${pngFiles.length} frames, encoding to GIF...`)

    // 4. 使用gifski编码成GIF
    await spawnFileWithBun('/usr/bin/gifski', [
      '--quiet',
      '-o',
      outPath,
      '--fps',
      '50',
      '--width',
      '512',
      '--height',
      '512',
      '--quality',
      '90',
      ...pngFiles,
    ])

    logger.info(`[tgs2gif] Successfully converted to ${outPath}`)
    return outPath
  }
  catch (error) {
    logger.error(`[tgs2gif] Conversion failed:`, error)
    throw error
  }
  finally {
    // 清理临时文件
    try {
      await runtimeFileIO.remove(tempDir, { recursive: true, force: true })
    }
    catch (cleanupError) {
      logger.warn(`[tgs2gif] Failed to cleanup temp dir:`, cleanupError)
    }
  }
}
